export const dummyPosts = [
  {
    id: '1',
    title: '주짓수 시작한 지 3개월 됐는데 질문있어요',
    content:
      '안녕하세요! 주짓수 시작한 지 3개월 됐는데 아직도 기본기가 너무 부족한 것 같아요. 다들 어떻게 연습하셨나요?안녕하세요! 주짓수 시작한 지 3개월 됐는데 아직도 기본기가 너무 부족한 것 같아요. 다들 어떻게 연습하셨나요?안녕하세요! 주짓수 시작한 지 3개월 됐는데 아직도 기본기가 너무 부족한 것 같아요. 다들 어떻게 연습하셨나요?',
    category: '일반 게시글',
    user_id: 'user1',
    nickname: '주짓수초보',
    avatar_url: '',
    image_url:
      'https://images.unsplash.com/photo-1555597673-b21d5c935865?w=400',
    view_count: 123,
    report_count: 0,
    created_at: '2026-04-21T10:00:00',
  },
  {
    id: '2',
    title: '강남 브라질리안 주짓수 아카데미 소개합니다',
    content:
      '안녕하세요! 강남구에 위치한 BJJ 아카데미입니다. 초보자부터 고급자까지 모두 환영합니다.',
    category: '도장 홍보',
    user_id: 'user2',
    nickname: '강남BJJ',
    avatar_url: '',
    image_url:
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400',
    view_count: 456,
    report_count: 0,
    created_at: '2026-04-20T10:00:00',
  },
  {
    id: '3',
    title: '첫 대회 나가봤습니다 후기',
    content:
      '드디어 첫 대회를 나가봤어요! 긴장도 많이 됐지만 정말 좋은 경험이었습니다. 다들 첫 대회 경험 어떠셨나요?',
    category: '일반 게시글',
    user_id: 'user3',
    nickname: '벨트도전자',
    avatar_url: '',
    image_url: '',
    view_count: 89,
    report_count: 0,
    created_at: '2026-04-19T14:00:00',
  },
  {
    id: '4',
    title: '홍대 주짓수 아카데미 3월 수강생 모집',
    content:
      '홍대 근처에 위치한 주짓수 도장입니다. 초보자 클래스 새로 개설했습니다. 많은 관심 부탁드립니다!',
    category: '도장 홍보',
    user_id: 'user4',
    nickname: '홍대BJJ',
    avatar_url: '',
    image_url:
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    view_count: 234,
    report_count: 0,
    created_at: '2026-04-18T09:00:00',
  },
  {
    id: '5',
    title: '주짓수 도복 추천해주세요',
    content:
      '이제 막 시작했는데 도복을 사려고 합니다. 입문자에게 추천하는 도복 브랜드가 있을까요?',
    category: '일반 게시글',
    user_id: 'user5',
    nickname: '도복고민중',
    avatar_url: '',
    image_url: '',
    view_count: 312,
    report_count: 0,
    created_at: '2026-04-17T11:00:00',
  },
  {
    id: '6',
    title: '송파 주짓수 아카데미 여성 클래스 오픈',
    content:
      '송파구에 위치한 주짓수 도장에서 여성 전용 클래스를 새로 오픈했습니다. 편안한 환경에서 배울 수 있어요!',
    category: '도장 홍보',
    user_id: 'user6',
    nickname: '송파BJJ',
    avatar_url: '',
    image_url:
      'https://images.unsplash.com/photo-1591117207239-788bf8de6c3b?w=400',
    view_count: 178,
    report_count: 0,
    created_at: '2026-04-16T13:00:00',
  },
  {
    id: '7',
    title: '가드 포지션 연습 팁 공유합니다',
    content:
      '가드 포지션 연습할 때 제가 효과 봤던 방법들 공유합니다. 특히 클로즈드 가드에서 스윕 연습이 중요한 것 같아요.',
    category: '일반 게시글',
    user_id: 'user7',
    nickname: '가드마스터',
    avatar_url: '',
    image_url:
      'https://images.unsplash.com/photo-1549476464-37392f717541?w=400',
    view_count: 567,
    report_count: 0,
    created_at: '2026-04-15T16:00:00',
  },
  {
    id: '8',
    title: '서초 브라질리안 주짓수 체험 클래스 안내',
    content:
      '서초구에서 운영 중인 주짓수 도장입니다. 이번 달 무료 체험 클래스를 진행합니다. 부담 없이 방문해주세요!',
    category: '도장 홍보',
    user_id: 'user8',
    nickname: '서초BJJ',
    avatar_url: '',
    image_url: '',
    view_count: 345,
    report_count: 0,
    created_at: '2026-04-14T10:00:00',
  },
  {
    id: '9',
    title: '운동 전 스트레칭 루틴 추천',
    content:
      '주짓수 전 부상 방지를 위한 스트레칭 루틴 공유합니다. 특히 목과 어깨 스트레칭이 중요합니다.',
    category: '일반 게시글',
    user_id: 'user9',
    nickname: '스트레칭왕',
    avatar_url: '',
    image_url:
      'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400',
    view_count: 423,
    report_count: 0,
    created_at: '2026-04-13T09:00:00',
  },
  {
    id: '10',
    title: '이태원 BJJ 센터 블랙벨트 세미나 개최',
    content:
      '이태원 BJJ 센터에서 브라질 블랙벨트 초청 세미나를 개최합니다. 많은 참여 부탁드립니다!',
    category: '도장 홍보',
    user_id: 'user10',
    nickname: '이태원BJJ',
    avatar_url: '',
    image_url: '',
    view_count: 678,
    report_count: 0,
    created_at: '2026-04-12T14:00:00',
  },
  {
    id: '11',
    title: '주짓수 하면서 체중 감량 성공했어요',
    content:
      '주짓수 시작한 지 6개월 만에 10kg 감량 성공했습니다! 다이어트 목적으로 시작했는데 이제는 진짜 매력에 빠졌어요.',
    category: '일반 게시글',
    user_id: 'user11',
    nickname: '다이어트성공',
    avatar_url: '',
    image_url:
      'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400',
    view_count: 891,
    report_count: 0,
    created_at: '2026-04-11T11:00:00',
  },
  {
    id: '12',
    title: '잠실 유도관 주짓수 클래스 오픈',
    content:
      '잠실에 위치한 유도관에서 주짓수 클래스를 새로 오픈했습니다. 유도 경험자 환영합니다!',
    category: '도장 홍보',
    user_id: 'user12',
    nickname: '잠실유도관',
    avatar_url: '',
    image_url: '',
    view_count: 156,
    report_count: 0,
    created_at: '2026-04-10T09:00:00',
  },
  {
    id: '13',
    title: '파란 벨트 땄습니다!!!',
    content:
      '드디어 파란 벨트를 받았어요! 2년 동안 정말 열심히 했는데 보람이 있네요. 다들 응원해주세요!',
    category: '일반 게시글',
    user_id: 'user13',
    nickname: '블루벨트달성',
    avatar_url: '',
    image_url:
      'https://images.unsplash.com/photo-1555597673-b21d5c935865?w=400',
    view_count: 1023,
    report_count: 0,
    created_at: '2026-04-09T18:00:00',
  },
  {
    id: '14',
    title: '부산 여행 중 훈련할 도장 추천받고 싶어요',
    content:
      '다음 주에 부산 출장 가는데 훈련할 수 있는 도장 아시는 분 계신가요? 하루 이틀 정도 훈련하고 싶어요.',
    category: '일반 게시글',
    user_id: 'user14',
    nickname: '부산출장자',
    avatar_url: '',
    image_url: '',
    view_count: 234,
    report_count: 0,
    created_at: '2026-04-08T15:00:00',
  },
  {
    id: '15',
    title: '마포구 주짓수 도장 4월 이벤트',
    content:
      '마포구 주짓수 도장에서 4월 신규 회원 등록 시 한 달 무료 이벤트를 진행합니다!',
    category: '도장 홍보',
    user_id: 'user15',
    nickname: '마포BJJ',
    avatar_url: '',
    image_url:
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400',
    view_count: 445,
    report_count: 0,
    created_at: '2026-04-07T10:00:00',
  },
  {
    id: '16',
    title: '노기 vs 기 어떤 게 더 재밌나요?',
    content:
      '노기랑 기 둘 다 해보신 분들 어떤 게 더 재밌으셨나요? 저는 노기가 더 재밌던데 다들 어떠세요?',
    category: '일반 게시글',
    user_id: 'user16',
    nickname: '노기vs기',
    avatar_url: '',
    image_url: '',
    view_count: 567,
    report_count: 0,
    created_at: '2026-04-06T14:00:00',
  },
  {
    id: '17',
    title: '강동구 BJJ 도장 오픈 기념 이벤트',
    content:
      '강동구에 새로 오픈한 BJJ 도장입니다. 오픈 기념으로 첫 달 50% 할인 이벤트를 진행합니다!',
    category: '도장 홍보',
    user_id: 'user17',
    nickname: '강동BJJ',
    avatar_url: '',
    image_url:
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    view_count: 334,
    report_count: 0,
    created_at: '2026-04-05T09:00:00',
  },
  {
    id: '18',
    title: '주짓수 훈련 파트너 구합니다 (강남)',
    content:
      '강남 지역에서 주말에 같이 훈련할 파트너 구합니다. 퍼플벨트 수준이고 주 2회 정도 훈련해요.',
    category: '일반 게시글',
    user_id: 'user18',
    nickname: '파트너구함',
    avatar_url: '',
    image_url: '',
    view_count: 189,
    report_count: 0,
    created_at: '2026-04-04T16:00:00',
  },
  {
    id: '19',
    title: '종로 주짓수 도장 키즈 클래스 모집',
    content:
      '종로구에 위치한 주짓수 도장에서 어린이 주짓수 클래스 수강생을 모집합니다. 7세 이상 가능합니다!',
    category: '도장 홍보',
    user_id: 'user19',
    nickname: '종로BJJ',
    avatar_url: '',
    image_url:
      'https://images.unsplash.com/photo-1591117207239-788bf8de6c3b?w=400',
    view_count: 278,
    report_count: 0,
    created_at: '2026-04-03T10:00:00',
  },
  {
    id: '20',
    title: '주짓수 시작 1년 회고',
    content:
      '주짓수를 시작한 지 딱 1년이 됐네요. 처음엔 정말 힘들었는데 지금은 없으면 안 될 것 같아요. 여러분도 꾸준히 하세요!',
    category: '일반 게시글',
    user_id: 'user20',
    nickname: '1년차회고',
    avatar_url: '',
    image_url:
      'https://images.unsplash.com/photo-1549476464-37392f717541?w=400',
    view_count: 934,
    report_count: 0,
    created_at: '2026-04-02T12:00:00',
  },
  {
    id: '21',
    title: '주짓수 영상 유튜브 채널 추천해주세요',
    content:
      '혼자 공부할 때 볼만한 주짓수 유튜브 채널 추천 부탁드립니다. 기술 설명이 잘 된 채널이면 좋겠어요.',
    category: '일반 게시글',
    user_id: 'user21',
    nickname: '유튜브고수',
    avatar_url: '',
    image_url: '',
    view_count: 445,
    report_count: 0,
    created_at: '2026-04-01T10:00:00',
  },
  {
    id: '22',
    title: '성동구 BJJ 도장 오픈했습니다',
    content:
      '성동구 성수동에 새로운 BJJ 도장이 오픈했습니다. 첫 달 무료 체험 가능합니다!',
    category: '도장 홍보',
    user_id: 'user22',
    nickname: '성수BJJ',
    avatar_url: '',
    image_url:
      'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400',
    view_count: 223,
    report_count: 0,
    created_at: '2026-03-31T09:00:00',
  },
  {
    id: '23',
    title: '주짓수 무릎 부상 조심하세요',
    content:
      '저번 주 훈련 중에 무릎 부상을 당했어요. 다들 훈련할 때 조심하시고 테이핑 꼭 하세요!',
    category: '일반 게시글',
    user_id: 'user23',
    nickname: '무릎부상자',
    avatar_url: '',
    image_url: '',
    view_count: 678,
    report_count: 0,
    created_at: '2026-03-30T14:00:00',
  },
  {
    id: '24',
    title: '관악구 주짓수 도장 주말 특별 클래스',
    content:
      '관악구 주짓수 도장에서 주말 특별 클래스를 진행합니다. 블랙벨트 사범님이 직접 지도합니다!',
    category: '도장 홍보',
    user_id: 'user24',
    nickname: '관악BJJ',
    avatar_url: '',
    image_url:
      'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400',
    view_count: 334,
    report_count: 0,
    created_at: '2026-03-29T10:00:00',
  },
  {
    id: '25',
    title: '주짓수 식단 관리 어떻게 하세요?',
    content:
      '주짓수 하면서 체중 관리를 위해 식단 조절 중인데 다들 어떻게 하시나요? 단백질 위주로 먹고 있어요.',
    category: '일반 게시글',
    user_id: 'user25',
    nickname: '식단관리중',
    avatar_url: '',
    image_url: '',
    view_count: 512,
    report_count: 0,
    created_at: '2026-03-28T11:00:00',
  },
  {
    id: '26',
    title: '은평구 주짓수 아카데미 신규 회원 모집',
    content:
      '은평구에 위치한 주짓수 아카데미입니다. 남녀노소 누구나 환영합니다. 첫 수업 무료!',
    category: '도장 홍보',
    user_id: 'user26',
    nickname: '은평BJJ',
    avatar_url: '',
    image_url:
      'https://images.unsplash.com/photo-1555597673-b21d5c935865?w=400',
    view_count: 189,
    report_count: 0,
    created_at: '2026-03-27T09:00:00',
  },
  {
    id: '27',
    title: '주짓수 대회 체급 어떻게 맞추나요?',
    content:
      '다음 달 대회 출전 예정인데 체급 맞추는 게 너무 힘드네요. 다들 어떻게 감량하시나요?',
    category: '일반 게시글',
    user_id: 'user27',
    nickname: '감량고민',
    avatar_url: '',
    image_url: '',
    view_count: 445,
    report_count: 0,
    created_at: '2026-03-26T15:00:00',
  },
  {
    id: '28',
    title: '노원구 BJJ 도장 여름 특강 안내',
    content:
      '노원구 BJJ 도장에서 여름 특강을 진행합니다. 기초부터 고급 기술까지 체계적으로 배울 수 있어요!',
    category: '도장 홍보',
    user_id: 'user28',
    nickname: '노원BJJ',
    avatar_url: '',
    image_url:
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400',
    view_count: 267,
    report_count: 0,
    created_at: '2026-03-25T10:00:00',
  },
  {
    id: '29',
    title: '퍼플벨트 취득 후기',
    content:
      '3년 만에 드디어 퍼플벨트를 취득했습니다! 정말 긴 여정이었지만 포기하지 않길 잘했어요.',
    category: '일반 게시글',
    user_id: 'user29',
    nickname: '퍼플달성',
    avatar_url: '',
    image_url:
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    view_count: 1234,
    report_count: 0,
    created_at: '2026-03-24T18:00:00',
  },
  {
    id: '30',
    title: '동대문구 주짓수 도장 오픈 이벤트',
    content:
      '동대문구에 새로 오픈한 주짓수 도장입니다. 오픈 기념으로 3개월 등록 시 1개월 무료!',
    category: '도장 홍보',
    user_id: 'user30',
    nickname: '동대문BJJ',
    avatar_url: '',
    image_url: '',
    view_count: 378,
    report_count: 0,
    created_at: '2026-03-23T09:00:00',
  },
];
